# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d490d8c7ce606b553177ecad0f5f66b60a57582e0b733bc2a1b9673ca1146f0857f88ff197e4e4d8c612aee24d2b2fc6fec4c5af3bf80476bf3bd6ea68726c

test:
  secret_key_base: feae7bdb937db4e87e0acefade4d00c2aad4220d60231757fd0f21dda0d9ca455f10d60dfb2c554f44a6bf43b336d1a59081a59d381ce9ec541f1084f76ecb2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
